name: check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install
        run: yarn install

      - name: start
        run: yarn github
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: update tmp
        run: |
          git config --global user.name "$user_name"
          git config --global user.email "$user_email"
          git init
          git add catch-news.json -f
          if [[ `git status --porcelain` ]]; then
            git commit -m "post new"
            git status --porcelain
            git push -f https://_:"$token"@github.com/a3510377/get-school-announce.git
          fi
        shell: bash
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Action
          user_email: action@github.com
